import {test} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
async function load() {
 const result=await build({entryPoints:['src/auth/identities.ts'],bundle:true,platform:'node',format:'cjs',write:false,plugins:[{name:'auth-boundaries',setup(b){
  b.onResolve({filter:/^(\.\/client|\.\/storage|\.\.\/platform\/router|@capacitor\/browser)$/},a=>({path:a.path,namespace:'fake'}));
  b.onLoad({filter:/.*/,namespace:'fake'},a=>({loader:'js',contents:a.path==='./client'?`export const nativeConfig={callback:'https://qa.example/auth/native/callback'};export const getNativeClient=()=>globalThis.__identity.client;`:a.path==='./storage'?`export const secureStorage={getItem:async k=>globalThis.__identity.disk.get(k)??null,setItem:async(k,v)=>{globalThis.__identity.disk.set(k,v)},removeItem:async k=>{globalThis.__identity.disk.delete(k)}};export const clearVerifiers=async()=>{};`:a.path.includes('router')?`export const router={replace:p=>globalThis.__identity.paths.push(p)};`:`export const Browser={open:async o=>globalThis.__identity.open.push(o),close:async()=>{}};`}));
 }}]});const mod={exports:{}};new Function('require','module','exports',result.outputFiles[0].text)(require,mod,mod.exports);return mod.exports;
}
function setup(){const s={disk:new Map(),paths:[],open:[],unlinked:[],exchanged:0,owner:'a',ids:[{id:'g',provider:'google'}]};s.client={auth:{getUser:async()=>({data:{user:{id:s.owner}}}),getUserIdentities:async()=>({data:{identities:s.ids}}),unlinkIdentity:async i=>{s.unlinked.push(i);return {}},linkIdentity:async()=>({data:{url:'https://accounts.example/authorize',flowId:'b'.repeat(32)}}),getSession:async()=>({data:{session:{user:{id:s.owner}}}}),exchangeCodeForSession:async()=>{s.exchanged++;return {data:{user:{id:s.owner}}}},setSession:async()=>({})}};globalThis.__identity=s;return s;}
test('last identity is blocked before SDK mutation; fresh two-provider state permits exact identity',async()=>{const s=setup(),a=await load();await assert.rejects(a.unlinkOAuthIdentity('google'),/last_identity/);assert.equal(s.unlinked.length,0);s.ids.push({id:'k',provider:'kakao'});await a.unlinkOAuthIdentity('google');assert.equal(s.unlinked[0].id,'g');});
test('both providers use durable callback flow; forged/replayed callbacks never exchange',async()=>{const s=setup(),a=await load();for(const provider of ['google','kakao']){await a.linkOAuthIdentity(provider);const pending=JSON.parse(s.disk.get('addi-native-link-attempt'));assert.equal(pending.provider,provider);assert.equal(await a.handleIdentityCallback('https://evil.example/?code=x'),false);const url=`https://qa.example/auth/native/callback?attempt=${pending.id}&code=synthetic`;assert.equal(await a.handleIdentityCallback(url),true);assert.equal(await a.handleIdentityCallback(url),false);}assert.equal(s.exchanged,2);assert.equal(s.paths.length,2);});
test('callback cannot exchange after account switch and failed start removes owner',async()=>{const s=setup(),a=await load();await a.linkOAuthIdentity('google');const pending=JSON.parse(s.disk.get('addi-native-link-attempt'));s.owner='b';await a.handleIdentityCallback(`https://qa.example/auth/native/callback?attempt=${pending.id}&code=x`);assert.equal(s.exchanged,0);assert.match(s.paths[0],/linkError/);s.client.auth.linkIdentity=async()=>({error:Error('disabled'),data:{}});await assert.rejects(a.linkOAuthIdentity('kakao'));assert.equal(s.disk.get('addi-native-link-owner'),undefined);});
test('logout cancellation drains an exchange even after callback nonce consumption',async()=>{
 const s=setup(),a=await load();let release;const gate=new Promise(r=>release=r);s.client.auth.exchangeCodeForSession=async()=>{await gate;return {data:{user:{id:'a'}}}};
 await a.linkOAuthIdentity('google');const pending=JSON.parse(s.disk.get('addi-native-link-attempt'));const callback=a.handleIdentityCallback(`https://qa.example/auth/native/callback?attempt=${pending.id}&code=x`);
 while(s.disk.has('addi-native-link-attempt'))await new Promise(r=>setImmediate(r));let drained=false;const cancel=a.cancelIdentityLink().then(()=>drained=true);await new Promise(r=>setImmediate(r));assert.equal(drained,false);release();await callback;await cancel;assert.equal(drained,true);assert.equal(s.disk.has('addi-native-link-owner'),false);
});
