/** Runtime substitutions are local to this Vite package; Next.js never loads them. */
export const nativeAliases = {
  '@/lib/supabase/config': 'src/adapters/supabase-config.ts',
  '@/lib/analytics/mixpanel': 'src/adapters/analytics-transport.ts',
  '@/lib/mood-navigation': 'src/platform/mood-navigation.ts',
  '@/lib/navigation-haptic': 'src/platform/haptic.ts',
  '@/lib/analytics/use-medication-registration-step': 'src/adapters/registration-analytics.ts',
  'next/link': 'src/platform/link.tsx',
  'next/image': 'src/platform/image.tsx',
  'next/navigation': 'src/platform/router.ts',
  '@/lib/repositories': 'src/adapters/repositories.ts',
  '@/lib/supabase/client': 'src/auth/client.ts',
  '@/lib/auth/client': 'src/adapters/auth.ts',
  '@/lib/push/preferences': 'src/adapters/push-preferences.ts',
  '@/lib/push/client': 'src/adapters/push.ts',
  '@/lib/notifications': 'src/adapters/notifications.ts',
  '@/lib/analytics/events': 'src/adapters/analytics.ts',
  '@/lib/account-deletion-local': 'src/adapters/account-deletion.ts',
  '@/lib/mood-draft': 'src/adapters/mood-draft.ts',
  '@/lib/indexed-db': 'src/adapters/legacy-storage.ts',
  '@/components/app-version-provider': 'src/adapters/app-version.ts',
};
