// No analytics transport in the fixture shell.
export type MoodAttemptHandle = { id: string; dateKey: string } | null;
export function trackScreenViewed(..._args: unknown[]) { return undefined; }
export function trackLoginStarted(..._args: unknown[]) { return undefined; }
export function trackLoginCompleted(..._args: unknown[]) { return undefined; }
export function startMedicationAddAttempt(..._args: unknown[]) { return undefined; }
export function ensureMedicationAddAttempt(..._args: unknown[]) { return undefined; }
export function trackMedicationRegistrationStepViewed(..._args: unknown[]) { return undefined; }
export function trackMedicationSaveClicked(..._args: unknown[]) { return undefined; }
export function trackMedicationRegistrationFailed(..._args: unknown[]) { return undefined; }
export function trackMedicationAdded(..._args: unknown[]) { return undefined; }
export function trackMedicationManagementOpened(..._args: unknown[]) { return undefined; }
export function trackMedicationScheduleEditOpened(..._args: unknown[]) { return undefined; }
export function trackMedicationScheduleUpdated(..._args: unknown[]) { return undefined; }
export function trackMedicationDeleteConfirmed(..._args: unknown[]) { return undefined; }
export function startMedicationTakeAttempt(..._args: unknown[]) { return undefined; }
export function setMedicationTakeBackend(..._args: unknown[]) { return undefined; }
export function trackMedicationTakeResult(..._args: unknown[]) { return undefined; }
export function trackMedicationTakeFailed(..._args: unknown[]) { return undefined; }
export function trackMedicationTakenOnce(..._args: unknown[]) { return undefined; }
export function startMoodAttempt(..._args: unknown[]) { return undefined; }
export function ensureMoodAttempt(..._args: unknown[]) { return null; }
export function endMoodAttempt(..._args: unknown[]) { return undefined; }
export function trackMoodStepCompleted(..._args: unknown[]) { return undefined; }
export function trackMoodResultViewed(..._args: unknown[]) { return undefined; }
export function trackMoodCompleted(..._args: unknown[]) { return undefined; }
export function trackMoodCatRewardRevealed(..._args: unknown[]) { return undefined; }
export function trackMoodAnalysisStarted(..._args: unknown[]) { return undefined; }
export function trackMoodAnalysisSucceeded(..._args: unknown[]) { return undefined; }
export function trackMoodAnalysisFailed(..._args: unknown[]) { return undefined; }
export function trackMoodSaveClicked(..._args: unknown[]) { return undefined; }
export function trackMoodSaveFailed(..._args: unknown[]) { return undefined; }
export function trackCatCollectionViewed(..._args: unknown[]) { return undefined; }
export function trackMoodReportViewed(..._args: unknown[]) { return undefined; }
export function trackMoodAnalysisRetried(..._args: unknown[]) { return undefined; }
export function trackMoodSaved(..._args: unknown[]) { return undefined; }
export function startVisitAddAttempt(..._args: unknown[]) { return undefined; }
export function ensureVisitAddAttempt(..._args: unknown[]) { return undefined; }
export function completeVisitAddAttempt(..._args: unknown[]) { return undefined; }
export function trackVisitAdded(..._args: unknown[]) { return undefined; }
export function trackHomeDatePickerOpened(..._args: unknown[]) { return undefined; }
export function trackHomeDateSelected(..._args: unknown[]) { return undefined; }
export function trackHomeDateTodayClicked(..._args: unknown[]) { return undefined; }
export function trackHomeDateChangeConfirmed(..._args: unknown[]) { return undefined; }
